// HOME UI
export const CHANGE_AUTHTYPE = 'boilerplate/Home/CHANGE_AUTHTYPE';
export const CHANGE_TABINDEX = 'boilerplate/Home/CHANGE_TABINDEX';
// Clapit
export const ASSIGN_CLAPIT_ACCOUNT_DATA = 'GLOBAL/ASSIGN_CLAPIT_ACCOUNT_DATA';
export const ASSIGN_DEVICE_TOKEN = 'GLOBAL/ASSIGN_DEVICE_TOKEN';
export const LOGGING_IN = 'GLOBAL/LOGGING_IN';
export const API_ERROR = 'GLOBAL/API_ERROR';
export const CLEAR_API_ERROR = 'GLOBAL/CLEAR_API_ERROR';
export const CLEAR_AUTH_ERROR = 'GLOBAL/CLEAR_AUTH_ERROR';
export const LOGOUT = 'GLOBAL/LOGOUT';
export const CLAP_POST = 'GLOBAL/CLAP_POST';

// Facebook
export const FACEBOOK_LOGOUT = 'GLOBAL/FACEBOOK_LOGOUT';
export const FACEBOOK_LOGOUT_SUCCESS = 'GLOBAL/FACEBOOK_LOGOUT_SUCCESS';
export const FACEBOOK_LOGOUT_ERROR = 'GLOBAL/FACEBOOK_LOGOUT_ERROR';
export const FACEBOOK_LOGIN_START = 'GLOBAL/FACEBOOK_LOGIN_START';
export const FACEBOOK_LOGIN_CANCEL = 'GLOBAL/FACEBOOK_LOGIN_CANCEL';

// Instagram
export const INSTAGRAM_LOGOUT = 'GLOBAL/INSTAGRAM_LOGOUT';
export const INSTAGRAM_LOGOUT_SUCCESS = 'GLOBAL/INSTAGRAM_LOGOUT_SUCCESS';
export const INSTAGRAM_LOGOUT_ERROR = 'GLOBAL/INSTAGRAM_LOGOUT_ERROR';

// Twitter
export const TWITTER_LOGOUT = 'GLOBAL/TWITTER_LOGOUT';
export const TWITTER_LOGOUT_SUCCESS = 'GLOBAL/TWITTER_LOGOUT_SUCCESS';
export const TWITTER_LOGOUT_ERROR = 'GLOBAL/TWITTER_LOGOUT_ERROR';

// Email
export const EMAIL_LOGOUT = 'GLOBAL/EMAIL_LOGOUT';
export const EMAIL_LOGOUT_SUCCESS = 'GLOBAL/EMAIL_LOGOUT_SUCCESS';
export const EMAIL_LOGOUT_ERROR = 'GLOBAL/EMAIL_LOGOUT_ERROR';
export const EMAIL_LOGIN_START = 'GLOBAL/EMAIL_LOGIN_START';
export const EMAIL_SIGNUP_START = 'GLOBAL/EMAIL_SIGNUP_START';
export const EMAIL_AUTH_DATA = 'GLOBAL/EMAIL_AUTH_DATA';
export const EMAIL_LOGIN_ERROR = 'GLOBAL/EMAIL_LOGIN_ERROR';

// Feed
export const FETCH_FEED_DATA = 'GLOBAL/FETCH_FEED_DATA';
export const FETCH_FEED_DATA_SUCCESS = 'GLOBAL/FETCH_FEED_DATA_SUCCESS';
export const FETCH_FEED_DATA_ERROR = 'GLOBAL/FETCH_FEED_DATA_ERROR';
export const FETCH_FEED_ITEM_REACTIONS = 'GLOBAL/FETCH_FEED_ITEM_REACTIONS';
export const FETCH_FEED_ITEM_REACTIONS_SUCCESS = 'GLOBAL/FETCH_FEED_ITEM_REACTIONS_SUCCESS';
export const FETCH_FEED_ITEM_REACTIONS_ERROR = 'GLOBAL/FETCH_FEED_ITEM_REACTIONS_ERROR';
export const CREATE_FEED_ITEM_REACTIONS = 'GLOBAL/CREATE_FEED_ITEM_REACTIONS';
export const CREATE_FEED_ITEM_REACTIONS_SUCCESS = 'GLOBAL/CREATE_FEED_ITEM_REACTIONS_SUCCESS';
export const CREATE_FEED_ITEM_REACTIONS_ERROR = 'GLOBAL/CREATE_FEED_ITEM_REACTIONS_ERROR';

export const UPDATE_FEED_ITEM_REACTIONS = 'GLOBAL/UPDATE_FEED_ITEM_REACTIONS';
export const UPDATE_FEED_ITEM_REACTIONS_SUCCESS = 'GLOBAL/UPDATE_FEED_ITEM_REACTIONS_SUCCESS';
export const UPDATE_FEED_ITEM_REACTIONS_ERROR = 'GLOBAL/UPDATE_FEED_ITEM_REACTIONS_ERROR';


export const FETCH_PROFILE_DATA = 'GLOBAL/FETCH_PROFILE_DATA';
export const FETCH_PROFILE_DATA_SUCCESS = 'GLOBAL/FETCH_PROFILE_DATA_SUCCESS';
export const FETCH_PROFILE_DATA_ERROR = 'GLOBAL/FETCH_PROFILE_DATA_ERROR';

export const FETCH_RECENT_POSTS = 'GLOBAL/FETCH_RECENT_POSTS';
export const FETCH_RECENT_POSTS_SUCCESS = 'GLOBAL/FETCH_RECENT_POSTS_SUCCESS';
export const FETCH_RECENT_POSTS_ERROR = 'GLOBAL/FETCH_RECENT_POSTS_ERROR';

export const FETCH_POPULAR_POSTS = 'GLOBAL/FETCH_POPULAR_POSTS';
export const FETCH_POPULAR_POSTS_SUCCESS = 'GLOBAL/FETCH_POPULAR_POSTS_SUCCESS';
export const FETCH_POPULAR_POSTS_ERROR = 'GLOBAL/FETCH_POPULAR_POSTS_ERROR';


export const FEED_ITEM_SHOW_DETAIL = 'GLOBAL/FEED_ITEM_SHOW_DETAIL';
export const FEED_ITEM_SHOW_REACTIONS = 'GLOBAL/FEED_ITEM_SHOW_REACTIONS';
export const FEED_ITEM_SHOW_PROFILE = 'GLOBAL/FEED_ITEM_SHOW_PROFILE';
export const FEED_ITEM_UPDATE = 'GLOBAL/FEED_ITEM_UPDATE';

// Facebook
export const ASSIGN_FACEBOOK_AUTH_DATA = 'GLOBAL/ASSIGN_FACEBOOK_AUTH_DATA';

// Twitter
export const ASSIGN_TWITTER_AUTH_DATA = 'GLOBAL/ASSIGN_TWITTER_AUTH_DATA';

// instagram
export const ASSIGN_INSTAGRAM_AUTH_DATA = 'GLOBAL/ASSIGN_INSTAGRAM_AUTH_DATA';

// Post
export const FETCH_GALLERY_MEDIAS = 'GLOBAL/FETCH_GALLERY_MEDIAS';
export const FETCH_GALLERY_MEDIAS_SUCCESS = 'GLOBAL/FETCH_GALLERY_MEDIAS_SUCCESS';
export const FETCH_GALLERY_MEDIAS_ERROR = 'GLOBAL/FETCH_GALLERY_MEDIAS_ERROR';

// Friends
export const FETCH_FRIENDS_DATA = 'GLOBAL/FETCH_FRIENDS_DATA';
export const FETCH_FRIENDS_DATA_SUCCESS = 'GLOBAL/FETCH_FRIENDS_DATA_SUCCESS';
export const FETCH_FRIENDS_DATA_ERROR = 'GLOBAL/FETCH_FRIENDS_DATA_ERROR';
export const SEARCH_FRIENDS = 'GLOBAL/SEARCH_FRIENDS';
export const SEARCH_FRIENDS_SUCCESS = 'GLOBAL/SEARCH_FRIENDS_SUCCESS';
export const SEARCH_FRIENDS_ERROR = 'GLOBAL/SEARCH_FRIENDS_ERROR';
export const SEARCH_HASH_TAGS = 'GLOBAL/SEARCH_HASH_TAGS';
export const SEARCH_HASH_TAGS_SUCCESS = 'GLOBAL/SEARCH_HASH_TAGS_SUCCESS';
export const SEARCH_HASH_TAGS_ERROR = 'GLOBAL/SEARCH_HASH_TAGS_ERROR';
export const DISMISS_FRIENDS_INVITE_MODAL = 'GLOBAL/DISMISS_FRIENDS_INVITE_MODAL';

// Notifications
export const FETCH_NOTIFICATIONS_DATA = 'GLOBAL/FETCH_NOTIFICATIONS_DATA';
export const FETCH_NOTIFICATIONS_SUCCESS = 'GLOBAL/FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'GLOBAL/FETCH_NOTIFICATIONS_ERROR';
export const MARK_NOTIFICATION_OLD = 'GLOBAL/MARK_NOTIFICATION_OLD';

// Tags
export const FETCH_TAG_DATA_START = 'GLOBAL/FETCH_TAG_DATA_START';
export const FETCH_TAG_DATA_SUCCESS = 'GLOBAL/FETCH_TAG_DATA_SUCCESS';
export const FETCH_TAG_DATA_ERROR = 'GLOBAL/FETCH_TAG_DATA_ERROR';
export const FETCH_HASHTAGS_START = 'GLOBAL/FETCH_HASHTAGS_START';
export const FETCH_HASHTAGS_SUCCESS = 'GLOBAL/FETCH_HASHTAGS_SUCCESS';
export const FETCH_HASHTAGS_ERROR = 'GLOBAL/FETCH_HASHTAGS_ERROR';
export const FETCH_USERNAMES_START = 'GLOBAL/FETCH_USERNAMES_START';
export const FETCH_USERNAMES_SUCCESS = 'GLOBAL/FETCH_USERNAMES_SUCCESS';
export const FETCH_USERNAMES_ERROR = 'GLOBAL/FETCH_USERNAMES_ERROR';

// Network
export const FETCH_FOLLOWERS = 'GLOBAL/FETCH_FOLLOWERS';
export const FETCH_FOLLOWERS_SUCCESS = 'GLOBAL/FETCH_FOLLOWERS_SUCCESS';
export const FETCH_FOLLOWERS_ERROR = 'GLOBAL/FETCH_FOLLOWERS_ERROR';
export const FETCH_FOLLOWING = 'GLOBAL/FETCH_FOLLOWING';
export const FETCH_FOLLOWING_SUCCESS = 'GLOBAL/FETCH_FOLLOWING_SUCCESS';
export const FETCH_FOLLOWING_ERROR = 'GLOBAL/FETCH_FOLLOWING_ERROR';
export const FETCH_CLAPS = 'GLOBAL/FETCH_CLAPS';
export const FETCH_CLAPS_SUCCESS = 'GLOBAL/FETCH_CLAPS_SUCCESS';
export const FETCH_CLAPS_ERROR = 'GLOBAL/FETCH_CLAPS_ERROR';
export const FOLLOW_USER = 'GLOBAL/FOLLOW_USER';
export const UNFOLLOW_USER = 'GLOBAL/UNFOLLOW_USER';
export const FETCH_CONTACTS_TO_FOLLOW = 'GLOBAL/FETCH_CONTACTS_TO_FOLLOW';
export const FETCH_CONTACTS_TO_FOLLOW_SUCCESS = 'GLOBAL/FETCH_CONTACTS_TO_FOLLOW_SUCCESS';
export const FETCH_CONTACTS_TO_FOLLOW_ERROR = 'GLOBAL/FETCH_CONTACTS_TO_FOLLOW_ERROR';
export const FETCH_CONTACTS_TO_INVITE = 'GLOBAL/FETCH_CONTACTS_TO_INVITE';
export const FETCH_CONTACTS_TO_INVITE_SUCCESS = 'GLOBAL/FETCH_CONTACTS_TO_INVITE_SUCCESS';
export const FETCH_CONTACTS_TO_INVITE_ERROR = 'GLOBAL/FETCH_CONTACTS_TO_INVITE_ERROR';
export const LOAD_DEVICE_CONTACTS = 'GLOBAL/LOAD_DEVICE_CONTACTS';
export const LOAD_DEVICE_CONTACTS_SUCCESS = 'GLOBAL/LOAD_DEVICE_CONTACTS_SUCCESS';
export const LOAD_DEVICE_CONTACTS_ERROR = 'GLOBAL/LOAD_DEVICE_CONTACTS_ERROR';
export const FETCH_INVITE_CONTACT = 'GLOBAL/FETCH_INVITE_CONTACT';
export const FETCH_INVITE_CONTACT_SUCCESS = 'GLOBAL/FETCH_INVITE_CONTACT_SUCCESS';
export const FETCH_INVITE_CONTACT_ERROR = 'GLOBAL/FETCH_INVITE_CONTACT_ERROR';
export const FETCH_SKIP_CONTACT = 'GLOBAL/FETCH_SKIP_CONTACT';
export const FETCH_SKIP_CONTACT_SUCCESS = 'GLOBAL/FETCH_SKIP_CONTACT_SUCCESS';
export const FETCH_SKIP_CONTACT_ERROR = 'GLOBAL/FETCH_SKIP_CONTACT_ERROR';
export const FETCH_INVITE_ALL_CONTACTS = 'GLOBAL/FETCH_INVITE_ALL_CONTACTS';
export const FETCH_INVITE_ALL_CONTACTS_SUCCESS = 'GLOBAL/FETCH_INVITE_ALL_CONTACTS_SUCCESS';
export const FETCH_INVITE_ALL_CONTACTS_ERROR = 'GLOBAL/FETCH_INVITE_ALL_CONTACTS_ERROR';

// Friendships
export const INIT_FRIENDSHIPS = 'GLOBAL/INIT_FRIENDSHIPS';

// Posts
export const FEED_ITEM_DELETE_SUCCESS = 'GLOBAL/FEED_ITEM_DELETE_SUCCESS';
export const FEED_ITEM_DELETE_ERROR = 'GLOBAL/FEED_ITEM_DELETE_ERROR';

// Posts
export const FILE_UPLOAD_START = 'GLOBAL/FILE_UPLOAD_START';
export const FILE_UPLOAD_SUCCESS = 'GLOBAL/FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_PROGRESS = 'GLOBAL/FILE_UPLOAD_PROGRESS';
export const FILE_UPLOAD_ERROR = 'GLOBAL/FILE_UPLOAD_ERROR';
export const FILE_UPLOAD_RESET = 'GLOBAL/FILE_UPLOAD_RESET';

// Preferences
export const PREFERENCES_SET = 'GLOBAL/PREFERENCES_SET';
