// leave off @2x/@3x
const images = {
  ico_post: require('../images/post_camera.png'),
  ico_best_on: require('../images/best_on.png'),
  ico_best_off: require('../images/best_off.png'),
  ico_alert_on: require('../images/alerts_on.png'),
  ico_alert_off: require('../images/alerts_off.png'),
  ico_new_on: require('../images/new_on.png'),
  ico_new_off: require('../images/new_off.png'),
  ico_me_on: require('../images/me_on.png'),
  ico_me_off: require('../images/me_off.png'),
  ico_magnifying_glass: require('../images/M-glass.png'),
  ico_main_signup: require('../images/main_signup.png'),
  purple_box_tutorial: require('../images/purple_box_tutorial.png'),
  signup_popup: require('../images/signup_popup.png'),
  clapit_top_bar: require('../images/clapit_top_bar.png'),
  clapit_top_bar_singit: require('../images/clapit_top_bar_singit.png'),
  ico_share: require('../images/Share.png'),
  ico_video: require('../images/Video_Outline.gif'),
  ico_video_loading: require('../images/Video_loading.gif'),
  ico_youtube: require('../images/YouTube-icon-full_color.png'),
  choose_video: require('../images/choose_video.png'),
  choose_photo: require('../images/choose_photo.png'),
  reaction_smiley: require('../images/reaction_smiley.png'),
  ico_mute: require('../images/mute.png'),
  ico_unmute: require('../images/unmute.png'),
  ico_settings_cog: require('../images/settings_cog.png'),
  ico_clap_bw: require('../images/clap_bw.png'),
  default_cover_image: require('../images/default_cover_image.jpg'),
  video_switch: require('../images/video_switch.png'),
  gold_hand: require('../images/GoldHand.gif'),
  ico_selfie_overlay_black: require('../images/ico_selfie_overlay_black.png'),
  danceit: require('../images/iamrichymon.jpg'),
  iamallwoman: require('../images/iamallwoman.png'),
  makemeamuse: require('../images/makemeamuse.jpg'),
  ico_info: require('../images/ico_info.png'),
  clap_flash: require('../images/clap_flash.png'),
  open_calls_logo: require('../images/open_calls_logo.png'),
  open_calls: require('../images/open_calls.png'),
  theo_video_preview: require('../images/TheoVideoPreview.jpg'),
  clapButtonForTint: require('../images/clapButtonForTint.png'),
  clapBlackOutline: require('../images/clapBlackOutline.png'),
  ico_avatar_overlay: require('../images/ico_avatar_overlay.png'),
  menu: require('../images/menu.png'),
  ico_grey_timestamp: require('../images/ico_grey_timestamp.png'),
  btn_following: require('../images/btn_following.png'),
  btn_follow: require('../images/btn_follow.png'),
  smallWhiteClap: require('../images/smallWhiteClap.png'),
  profileFollow: require('../images/profileFollow.png'),
  profileFollowing: require('../images/profileFollowing.png'),
  btn_notifications_following: require('../images/btn_notifications_following.png'),
  btn_notifications_follow: require('../images/btn_notifications_follow.png'),
  login_screen: require('../images/login_screen.png'),
};

export default images;
