// Navigation
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH'
export const NAVIGATION_POP = 'NAVIGATION_POP'
export const NAVIGATION_REPLACE = 'NAVIGATION_REPLACE'

// Clapit
export const ASSIGN_CLAPIT_ACCOUNT_DATA = 'ASSIGN_CLAPIT_ACCOUNT_DATA'
export const ASSIGN_DEVICE_TOKEN = 'ASSIGN_DEVICE_TOKEN'
export const LOGGING_IN = 'LOGGING_IN'
export const API_ERROR = 'API_ERROR'
export const CLEAR_API_ERROR = 'CLEAR_API_ERROR'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const LOGOUT = 'LOGOUT'
export const CLAP_POST = 'CLAP_POST'

// Facebook
export const FACEBOOK_LOGOUT = 'FACEBOOK_LOGOUT'
export const FACEBOOK_LOGOUT_SUCCESS = 'FACEBOOK_LOGOUT_SUCCESS'
export const FACEBOOK_LOGOUT_ERROR = 'FACEBOOK_LOGOUT_ERROR'
export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START'
export const FACEBOOK_LOGIN_CANCEL = 'FACEBOOK_LOGIN_CANCEL'

// Instagram
export const INSTAGRAM_LOGOUT = 'INSTAGRAM_LOGOUT'
export const INSTAGRAM_LOGOUT_SUCCESS = 'INSTAGRAM_LOGOUT_SUCCESS'
export const INSTAGRAM_LOGOUT_ERROR = 'INSTAGRAM_LOGOUT_ERROR'

// Twitter
export const TWITTER_LOGOUT = 'TWITTER_LOGOUT'
export const TWITTER_LOGOUT_SUCCESS = 'TWITTER_LOGOUT_SUCCESS'
export const TWITTER_LOGOUT_ERROR = 'TWITTER_LOGOUT_ERROR'

// Email
export const EMAIL_LOGOUT = 'EMAIL_LOGOUT'
export const EMAIL_LOGOUT_SUCCESS = 'EMAIL_LOGOUT_SUCCESS'
export const EMAIL_LOGOUT_ERROR = 'EMAIL_LOGOUT_ERROR'
export const EMAIL_LOGIN_START = 'EMAIL_LOGIN_START'
export const EMAIL_SIGNUP_START = 'EMAIL_SIGNUP_START'
export const EMAIL_AUTH_DATA = 'EMAIL_AUTH_DATA'
export const EMAIL_LOGIN_ERROR = 'EMAIL_LOGIN_ERROR'

// Feed
export const FETCH_FEED_DATA = 'FETCH_FEED_DATA'
export const FETCH_FEED_DATA_SUCCESS = 'FETCH_FEED_DATA_SUCCESS'
export const FETCH_FEED_DATA_ERROR = 'FETCH_FEED_DATA_ERROR'
export const FETCH_FEED_ITEM_REACTIONS = 'FETCH_FEED_ITEM_REACTIONS'
export const FETCH_FEED_ITEM_REACTIONS_SUCCESS = 'FETCH_FEED_ITEM_REACTIONS_SUCCESS'
export const FETCH_FEED_ITEM_REACTIONS_ERROR = 'FETCH_FEED_ITEM_REACTIONS_ERROR'
export const CREATE_FEED_ITEM_REACTIONS = "CREATE_FEED_ITEM_REACTIONS"
export const CREATE_FEED_ITEM_REACTIONS_SUCCESS = "CREATE_FEED_ITEM_REACTIONS_SUCCESS"
export const CREATE_FEED_ITEM_REACTIONS_ERROR = "CREATE_FEED_ITEM_REACTIONS_ERROR"

export const UPDATE_FEED_ITEM_REACTIONS = "UPDATE_FEED_ITEM_REACTIONS"
export const UPDATE_FEED_ITEM_REACTIONS_SUCCESS = "UPDATE_FEED_ITEM_REACTIONS_SUCCESS"
export const UPDATE_FEED_ITEM_REACTIONS_ERROR = "UPDATE_FEED_ITEM_REACTIONS_ERROR"


export const FETCH_PROFILE_DATA = 'FETCH_PROFILE_DATA'
export const FETCH_PROFILE_DATA_SUCCESS = 'FETCH_PROFILE_DATA_SUCCESS'
export const FETCH_PROFILE_DATA_ERROR = 'FETCH_PROFILE_DATA_ERROR'

export const FETCH_RECENT_POSTS = 'FETCH_RECENT_POSTS'
export const FETCH_RECENT_POSTS_SUCCESS = 'FETCH_RECENT_POSTS_SUCCESS'
export const FETCH_RECENT_POSTS_ERROR = 'FETCH_RECENT_POSTS_ERROR'

export const FETCH_POPULAR_POSTS = 'FETCH_POPULAR_POSTS'
export const FETCH_POPULAR_POSTS_SUCCESS = 'FETCH_POPULAR_POSTS_SUCCESS'
export const FETCH_POPULAR_POSTS_ERROR = 'FETCH_POPULAR_POSTS_ERROR'


export const FEED_ITEM_SHOW_DETAIL = 'FEED_ITEM_SHOW_DETAIL'
export const FEED_ITEM_SHOW_REACTIONS = 'FEED_ITEM_SHOW_REACTIONS'
export const FEED_ITEM_SHOW_PROFILE = 'FEED_ITEM_SHOW_PROFILE'
export const FEED_ITEM_UPDATE = 'FEED_ITEM_UPDATE'

// Facebook
export const ASSIGN_FACEBOOK_AUTH_DATA = 'ASSIGN_FACEBOOK_AUTH_DATA'

// Twitter
export const ASSIGN_TWITTER_AUTH_DATA = 'ASSIGN_TWITTER_AUTH_DATA'

// instagram
export const ASSIGN_INSTAGRAM_AUTH_DATA = 'ASSIGN_INSTAGRAM_AUTH_DATA'

// Post
export const FETCH_GALLERY_MEDIAS = 'FETCH_GALLERY_MEDIAS'
export const FETCH_GALLERY_MEDIAS_SUCCESS = 'FETCH_GALLERY_MEDIAS_SUCCESS'
export const FETCH_GALLERY_MEDIAS_ERROR = 'FETCH_GALLERY_MEDIAS_ERROR'

//Friends
export const FETCH_FRIENDS_DATA = 'FETCH_FRIENDS_DATA'
export const FETCH_FRIENDS_DATA_SUCCESS = 'FETCH_FRIENDS_DATA_SUCCESS'
export const FETCH_FRIENDS_DATA_ERROR = 'FETCH_FRIENDS_DATA_ERROR'
export const SEARCH_FRIENDS = 'SEARCH_FRIENDS'
export const SEARCH_FRIENDS_SUCCESS = 'SEARCH_FRIENDS_SUCCESS'
export const SEARCH_FRIENDS_ERROR = 'SEARCH_FRIENDS_ERROR'
export const SEARCH_HASH_TAGS = 'SEARCH_HASH_TAGS'
export const SEARCH_HASH_TAGS_SUCCESS = 'SEARCH_HASH_TAGS_SUCCESS'
export const SEARCH_HASH_TAGS_ERROR = 'SEARCH_HASH_TAGS_ERROR'
export const DISMISS_FRIENDS_INVITE_MODAL = 'DISMISS_FRIENDS_INVITE_MODAL'

//Notifications
export const FETCH_NOTIFICATIONS_DATA = 'FETCH_NOTIFICATIONS_DATA'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR'
export const MARK_NOTIFICATION_OLD = 'MARK_NOTIFICATION_OLD'

// Tags
export const FETCH_TAG_DATA_START = 'FETCH_TAG_DATA_START'
export const FETCH_TAG_DATA_SUCCESS = 'FETCH_TAG_DATA_SUCCESS'
export const FETCH_TAG_DATA_ERROR = 'FETCH_TAG_DATA_ERROR'// Feed
export const FETCH_HASHTAGS_START = 'FETCH_HASHTAGS_START'
export const FETCH_HASHTAGS_SUCCESS = 'FETCH_HASHTAGS_SUCCESS'
export const FETCH_HASHTAGS_ERROR = 'FETCH_HASHTAGS_ERROR'

// Network
export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS'
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS'
export const FETCH_FOLLOWERS_ERROR = 'FETCH_FOLLOWERS_ERROR'
export const FETCH_FOLLOWING = 'FETCH_FOLLOWING'
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS'
export const FETCH_FOLLOWING_ERROR = 'FETCH_FOLLOWING_ERROR'
export const FETCH_CLAPS = 'FETCH_CLAPS'
export const FETCH_CLAPS_SUCCESS = 'FETCH_CLAPS_SUCCESS'
export const FETCH_CLAPS_ERROR = 'FETCH_CLAPS_ERROR'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const FETCH_CONTACTS_TO_FOLLOW = 'FETCH_CONTACTS_TO_FOLLOW'
export const FETCH_CONTACTS_TO_FOLLOW_SUCCESS = 'FETCH_CONTACTS_TO_FOLLOW_SUCCESS'
export const FETCH_CONTACTS_TO_FOLLOW_ERROR = 'FETCH_CONTACTS_TO_FOLLOW_ERROR'
export const FETCH_CONTACTS_TO_INVITE = 'FETCH_CONTACTS_TO_INVITE'
export const FETCH_CONTACTS_TO_INVITE_SUCCESS = 'FETCH_CONTACTS_TO_INVITE_SUCCESS'
export const FETCH_CONTACTS_TO_INVITE_ERROR = 'FETCH_CONTACTS_TO_INVITE_ERROR'
export const LOAD_DEVICE_CONTACTS = 'LOAD_DEVICE_CONTACTS'
export const LOAD_DEVICE_CONTACTS_SUCCESS = 'LOAD_DEVICE_CONTACTS_SUCCESS'
export const LOAD_DEVICE_CONTACTS_ERROR = 'LOAD_DEVICE_CONTACTS_ERROR'
export const FETCH_INVITE_CONTACT = 'FETCH_INVITE_CONTACT'
export const FETCH_INVITE_CONTACT_SUCCESS = 'FETCH_INVITE_CONTACT_SUCCESS'
export const FETCH_INVITE_CONTACT_ERROR = 'FETCH_INVITE_CONTACT_ERROR'
export const FETCH_SKIP_CONTACT = 'FETCH_SKIP_CONTACT'
export const FETCH_SKIP_CONTACT_SUCCESS = 'FETCH_SKIP_CONTACT_SUCCESS'
export const FETCH_SKIP_CONTACT_ERROR = 'FETCH_SKIP_CONTACT_ERROR'
export const FETCH_INVITE_ALL_CONTACTS = 'FETCH_INVITE_ALL_CONTACTS'
export const FETCH_INVITE_ALL_CONTACTS_SUCCESS = 'FETCH_INVITE_ALL_CONTACTS_SUCCESS'
export const FETCH_INVITE_ALL_CONTACTS_ERROR = 'FETCH_INVITE_ALL_CONTACTS_ERROR'

// Friendships
export const INIT_FRIENDSHIPS = 'INIT_FRIENDSHIPS'

// Posts
export const FEED_ITEM_DELETE_SUCCESS = 'FEED_ITEM_DELETE_SUCCESS'
export const FEED_ITEM_DELETE_ERROR = 'FEED_ITEM_DELETE_ERROR'

// Posts
export const FILE_UPLOAD_START = 'FILE_UPLOAD_START'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS'
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR'
export const FILE_UPLOAD_RESET = 'FILE_UPLOAD_RESET'

// Preferences
export const PREFERENCES_SET = 'PREFERENCES_SET'